# Generated by Django 2.0.6 on 2018-06-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('skladnik1', models.CharField(max_length=50)),
                ('skladnik2', models.CharField(max_length=50)),
                ('skladnik3', models.CharField(max_length=50)),
                ('skladnik4', models.CharField(max_length=50)),
                ('skladnik5', models.CharField(max_length=50)),
                ('skladnik6', models.CharField(max_length=50)),
                ('czas', models.FloatField()),
                ('poziom', models.FloatField()),
                ('opis', models.TextField()),
                ('data', models.DateTimeField()),
                ('zdjecie', models.ImageField(upload_to='')),
            ],
        ),
    ]
