# Generated by Django 2.0.6 on 2018-06-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tytuł')),
                ('mail', models.CharField(max_length=50, verbose_name='E-mail')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('text', models.TextField(verbose_name='Treść')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Wiadomość do Admina',
                'verbose_name_plural': 'Wiadomości do Admina',
            },
        ),
    ]
